---
- name: setting some variables
  include_vars: blcr_vars.yml
  tags:
    - blcr

- name: installing dependencies
  sudo: true
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "@Development tools"
    - kernel-devel
    - kernel-headers
    - rpm-build
  tags:
    - blcr

- name: installing source rpm
  command: /usr/bin/rpm --install {{ blcr_url }}
  args:
    creates: "{{ blcr_spec }}"
  tags:
    - blcr

- name: patching sources
  patch:
    dest: "{{ blcr_spec }}"
    src: blcr_spec.patch
    remote_src: false
  tags:
    - blcr

- name: building
  command: /usr/bin/rpmbuild -bb {{ blcr_spec }} --define 'with_multilib 0'
  args:
    creates: "{{ blcr_bin }}"
  tags:
    - blcr

- name: installing
  sudo: true
  yum:
    state: present
    name: "{{ item }}"
  with_items: blcr_pkgs
  when: item != ''
  tags:
    - blcr

- name: loading modules
  sudo: true
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - blcr_imports
    - blcr
  when: blcr.modules is defined and blcr.modules
  tags:
    - blcr

- name: registering modules to load at boot
  sudo: true
  lineinfile:
    dest: /etc/modules-load.d/blcr.conf
    create: true
    line: "{{ item }}"
    state: present
  with_items:
    - blcr_imports
    - blcr
  tags:
    - blcr
